(function(){
  "use strict";
  var tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
  var initData=tg&&tg.initData?tg.initData:"";
  var base=(window.QUIZ_API_BASE||document.querySelector('meta[name="quiz-api-base"]').content||"").replace(/\/$/,"");
  function el(id){return document.getElementById(id)}
  function request(path,options){options=options||{};options.headers=Object.assign({"X-Telegram-Init-Data":initData},options.headers||{});return miniappFetch(base+path,options).then(function(response){return response.ok?response.json():response.json().catch(function(){return{}}).then(function(body){var error=new Error(body.detail||"অনুরোধ ব্যর্থ হয়েছে");error.status=response.status;throw error})})}
  function text(value,fallback){return value===null||value===undefined||value===""?(fallback||"—"):String(value)}
  function clear(node){while(node.firstChild)node.removeChild(node.firstChild)}
  function metric(label,value){var wrap=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");wrap.className="metric";dt.textContent=label;dd.textContent=text(value);wrap.append(dt,dd);return wrap}
  function showError(error){el("workspace").classList.add("hidden");el("state").classList.remove("hidden");el("state").textContent=error.status===403?"এই Telegram অ্যাকাউন্টে অ্যাডমিন অনুমতি নেই।":error.status===401?"Telegram-এর ভিতর থেকে অ্যাডমিন প্যানেল খুলুন।":"অপারেশন ডেটা এখন লোড করা যাচ্ছে না।"}
  function load(){el("state").classList.remove("hidden");el("state").textContent="অপারেশন ডেটা লোড হচ্ছে…";Promise.all([request("/api/admin/operations"),request("/api/admin/resources/reviews?limit=50"),request("/api/admin/questions/reviews?limit=50")]).then(function(results){renderOperations(results[0]);renderResources(results[1]);renderQuestions(results[2]);el("state").classList.add("hidden");el("workspace").classList.remove("hidden")}).catch(showError)}
  function renderOperations(data){var metrics=el("metrics"),resources=data.resources||{};clear(metrics);[["ডেটাবেস",data.databaseConnectivity?"সচল":"সমস্যা"],["স্কিমা",data.schemaReady?"প্রস্তুত":"অসম্পূর্ণ"],["আজ ব্যর্থ রান",data.failedRunsToday||0],["অজানা পোস্টিং",data.postingUnknown||0],["যাচাইকৃত রিসোর্স",resources.activeVerified||0],["বাকি রিভিউ",resources.pendingReviews||0]].forEach(function(item){metrics.appendChild(metric(item[0],item[1]))})}
  function card(title,lines){var box=document.createElement("article"),heading=document.createElement("h3");box.className="review";heading.textContent=text(title,"নামহীন আইটেম");box.appendChild(heading);lines.forEach(function(line){var p=document.createElement("p");p.textContent=line;box.appendChild(p)});return box}
  function actionButton(label,action,handler){var button=document.createElement("button");button.type="button";button.dataset.action=action;button.textContent=label;button.addEventListener("click",function(){if(!window.confirm("এই সিদ্ধান্ত নিশ্চিত করবেন?"))return;button.disabled=true;handler().then(load).catch(showError).finally(function(){button.disabled=false})});return button}
  function renderResources(data){var rows=Array.isArray(data.rows)?data.rows:[],list=el("resource-list");clear(list);el("resource-count").textContent=text(data.total||0)+"টি";if(!rows.length){list.appendChild(empty());return}rows.forEach(function(row){var box=card(row.title,[text(row.subjectKey)+" · "+text(row.chapter),text(row.type)+" · "+text(row.status),text(row.url)]),actions=document.createElement("div");actions.className="actions";[["অনুমোদন","approve"],["প্রত্যাখ্যান","reject"],["আর্কাইভ","archive"]].forEach(function(item){actions.appendChild(actionButton(item[0],item[1],function(){return request("/api/admin/resources/"+encodeURIComponent(row.resourceId)+"/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:initData,decision:item[1]})})}))});box.appendChild(actions);list.appendChild(box)})}
  function renderQuestions(data){var rows=Array.isArray(data.rows)?data.rows:Array.isArray(data.items)?data.items:[],list=el("question-list");clear(list);el("question-count").textContent=text(data.total||rows.length)+"টি";if(!rows.length){list.appendChild(empty());return}rows.forEach(function(row){var box=card(row.question||row.questionText||row.caseId,[text(row.subjectKey||row.subject),text(row.reason||row.status),text(row.details||row.reportCount)]);list.appendChild(box)})}
  function empty(){var p=document.createElement("p");p.className="empty";p.textContent="এখন পর্যালোচনার অপেক্ষায় কিছু নেই।";return p}
  el("refresh").addEventListener("click",load);if(tg){try{tg.ready();tg.expand()}catch(error){}}if(initData)load();else showError({status:401});
})();
