(function(){
  "use strict";
  var tg=window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;
  if(tg){tg.ready();tg.expand();if(typeof tg.enableClosingConfirmation==="function")tg.enableClosingConfirmation()}
  var params=new URLSearchParams(location.search),testId=params.get("test")||"",requestedExam=params.get("exam")||"",resumeClientId=params.get("clientAttempt")||"",resumeAttemptId=params.get("attempt")||"";
  var apiBase=(document.querySelector('meta[name="quiz-api-base"]')||{}).content||"";
  var initData=tg&&tg.initData?tg.initData:"";
  var instance=null,sections=[],flat=[],attempt=null,currentSectionId=null,currentIndex=0;
  var answers={},marked={},bookmarked={},responseTimes={},questionOpenedAt=Date.now(),timerHandle=null;
  var syncing=false,syncQueued=false,syncPromise=null,autoSubmitPending=false,retryAction=loadInstance;
  var screens=["loading","catalog","empty","error","intro","test","result"];
  var catalogRows=[],catalogAttempts={},pyqRows=[],pyqTotal=0,pyqOffset=0,pyqLoading=false;
  function byId(id){return document.getElementById(id)}
  function api(path){return apiBase.replace(/\/$/,"")+path}
  function show(name){screens.forEach(function(item){byId("screen-"+item).classList.toggle("hidden",item!==name)});byId("timer").classList.toggle("hidden",name!=="test");if(name!=="test")clearInterval(timerHandle);var target=byId("screen-"+name);if(target)target.focus&&target.focus()}
  function request(path,options){if(typeof window.miniappRequest!=="function")return Promise.reject({category:"UNKNOWN"});return window.miniappRequest(api(path),options||{})}
  function errorCategory(error){return String(error&&error.category||"UNKNOWN").toUpperCase()}
  function safeErrorCopy(error){if(typeof window.miniappErrorMessage==="function")return window.miniappErrorMessage(error);return"অনুরোধটি সম্পন্ন করা যায়নি। একটু পরে আবার চেষ্টা করুন।"}
  function uuid(){if(crypto&&crypto.randomUUID)return crypto.randomUUID();var b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;var h=Array.from(b,function(v){return v.toString(16).padStart(2,"0")}).join("");return h.slice(0,8)+"-"+h.slice(8,12)+"-"+h.slice(12,16)+"-"+h.slice(16,20)+"-"+h.slice(20)}
  function validTestId(value){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
  function serverDraft(){if(!validTestId(resumeClientId)||!validTestId(resumeAttemptId))return null;return{testId:testId,attemptId:resumeAttemptId,clientAttemptId:resumeClientId,currentSectionId:null,currentIndex:0,answers:{},marked:{},responseTimes:{},deadlineAt:null,savedAt:Date.now()}}
  function draftKey(){return "telegram-mock-draft:"+testId}
  function readDraft(){try{var value=JSON.parse(localStorage.getItem(draftKey())||"null");if(!value||value.testId!==testId||Date.now()-value.savedAt>7*86400000)return serverDraft();return value}catch(e){return serverDraft()}}
  function saveDraft(){if(!testId)return;try{localStorage.setItem(draftKey(),JSON.stringify({testId:testId,attemptId:attempt&&attempt.attemptId||null,clientAttemptId:attempt&&attempt.clientAttemptId||null,currentSectionId:currentSectionId,currentIndex:currentIndex,answers:answers,marked:marked,responseTimes:responseTimes,deadlineAt:attempt&&attempt.deadlineAt||null,savedAt:Date.now()}))}catch(e){}}
  function discardDraft(){resumeClientId="";resumeAttemptId="";try{localStorage.removeItem(draftKey())}catch(e){}}
  function restoreDraft(value){answers=value.answers||{};marked=value.marked||{};responseTimes=value.responseTimes||{};currentSectionId=value.currentSectionId||sections[0].sectionInstanceId;currentIndex=Math.max(0,Number(value.currentIndex)||0);attempt={attemptId:value.attemptId||null,clientAttemptId:value.clientAttemptId||uuid(),deadlineAt:value.deadlineAt||null}}
  function flatten(){flat=[];sections.forEach(function(section){(section.questions||[]).forEach(function(question){flat.push({section:section,question:question})})})}
  function loadInstance(){retryAction=testId?loadInstance:loadCatalog;show("loading");byId("loading-copy").textContent="পরীক্ষা লোড হচ্ছে...";if(!validTestId(testId)){loadCatalog();return}request("/api/tests/instances/"+encodeURIComponent(testId)).then(function(data){instance=data;sections=Array.isArray(data.sections)?data.sections:[];flatten();if(!sections.length||!flat.length){show("empty");byId("empty-copy").textContent="এই পরীক্ষায় এখনও কোনো প্রকাশিত প্রশ্ন নেই।";return}renderIntro()}).catch(function(error){showError(errorCategory(error)==="NOT_FOUND"?"পরীক্ষাটি পাওয়া যায়নি বা এখনও প্রকাশিত হয়নি।":safeErrorCopy(error))})}
  function loadCatalog(){retryAction=loadCatalog;var publicCatalog=request("/api/tests/catalog?limit=100"),attemptHistory=initData?request("/api/tests/attempts/recent?limit=100",{headers:{"X-Telegram-Init-Data":initData},cache:"no-store"}).catch(function(){return{rows:[]}}):Promise.resolve({rows:[]});Promise.all([publicCatalog,attemptHistory]).then(function(results){catalogRows=Array.isArray(results[0].rows)?results[0].rows:[];catalogAttempts={};(results[1].rows||[]).forEach(function(row){if(!catalogAttempts[row.testInstanceId])catalogAttempts[row.testInstanceId]=row});if(requestedExam&&!byId("catalog-search").value)byId("catalog-search").value=requestedExam;if(requestedExam&&!byId("pyq-exam").value)byId("pyq-exam").value=requestedExam;renderCatalog();show("catalog");loadPyq(true)}).catch(function(error){showError(safeErrorCopy(error))})}
  function catalogTypeLabel(value){return{full_mock:"পূর্ণ মক",sectional_mock:"বিভাগীয় মক",previous_year:"পূর্ববর্তী বছরের প্রশ্ন",previous_year_style:"PYQ-ধাঁচ",subject:"বিষয়ভিত্তিক",chapter:"অধ্যায়ভিত্তিক"}[value]||value||"মক পরীক্ষা"}
  function renderCatalog(){var query=byId("catalog-search").value.trim().toLowerCase(),type=byId("catalog-type").value,list=byId("catalog-list");list.textContent="";var rows=catalogRows.filter(function(row){var haystack=[row.title,row.examName,row.examKey,row.subjectKey,catalogTypeLabel(row.testType)].join(" ").toLowerCase();return(!type||row.testType===type)&&(!query||haystack.includes(query))});if(!rows.length){var empty=document.createElement("p");empty.textContent="এই ফিল্টারে কোনো প্রকাশিত পরীক্ষা নেই।";list.appendChild(empty);return}rows.forEach(function(row){var state=catalogAttempts[row.testInstanceId]||null,card=document.createElement("article"),title=document.createElement("h3"),meta=document.createElement("p"),badges=document.createElement("div"),link=document.createElement("a"),badgeTexts=[String(row.questionCount||0)+" প্রশ্ন",row.timeLimitSeconds?Math.ceil(row.timeLimitSeconds/60)+" মিনিট":"সময়সীমা নেই",row.negativeMarksPerWrong?"নেগেটিভ −"+row.negativeMarksPerWrong:"নেগেটিভ নেই",row.availability==="open"?"এখন খোলা":"প্রকাশিত"];card.className="catalog-item";title.textContent=row.title||"প্রকাশিত পরীক্ষা";meta.textContent=[row.examName||row.examKey,row.subjectKey,catalogTypeLabel(row.testType)].filter(Boolean).join(" · ");badges.className="catalog-badges";if(state&&state.status==="in_progress")badgeTexts.push(String(state.answeredCount||0)+" / "+String(state.questionCount||row.questionCount||0)+" উত্তর · অসম্পূর্ণ");else if(state&&(state.status==="submitted"||state.status==="auto_submitted"))badgeTexts.push("শেষ নেট স্কোর "+String(state.netMarks||0));badgeTexts.forEach(function(text){var badge=document.createElement("span");badge.textContent=text;badges.appendChild(badge)});link.className="btn primary";link.href="mock.html?test="+encodeURIComponent(row.testInstanceId);link.textContent="পরীক্ষা খুলুন";if(state&&state.status==="in_progress"&&validTestId(state.clientAttemptId)&&validTestId(state.attemptId)){link.href+="&clientAttempt="+encodeURIComponent(state.clientAttemptId)+"&attempt="+encodeURIComponent(state.attemptId);link.textContent="চালিয়ে যান"}else if(state&&(state.status==="submitted"||state.status==="auto_submitted"))link.textContent="আবার পরীক্ষা দিন";card.append(title,meta,badges,link);list.appendChild(card)})}
  function pyqParams(){var params=new URLSearchParams({limit:"100",offset:String(pyqOffset)}),exam=byId("pyq-exam").value.trim(),year=byId("pyq-year").value,language=byId("pyq-language").value;if(exam)params.set("exam",exam);if(year)params.set("year",year);if(language)params.set("language",language);return params}
  function loadPyq(reset){if(pyqLoading)return;if(reset){pyqRows=[];pyqTotal=0;pyqOffset=0;byId("pyq-hierarchy").textContent=""}pyqLoading=true;byId("btn-pyq-filter").disabled=true;byId("btn-pyq-more").disabled=true;byId("pyq-status").textContent="যাচাই করা PYQ প্রশ্ন লোড হচ্ছে...";request("/api/previous-year?"+pyqParams().toString()).then(function(data){var incoming=Array.isArray(data.rows)?data.rows:[];var known=new Set(pyqRows.map(function(row){return row.provenanceId||row.questionId}));incoming.forEach(function(row){var key=row.provenanceId||row.questionId;if(key&&!known.has(key)){known.add(key);pyqRows.push(row)}});pyqTotal=Math.max(0,Number(data.total)||pyqRows.length);pyqOffset+=incoming.length;renderPyq()}).catch(function(error){byId("pyq-status").textContent=errorCategory(error)==="INVALID_REQUEST"?"ফিল্টারটি ঠিক করে আবার চেষ্টা করুন।":"PYQ প্রশ্নব্যাংক এখন লোড করা যাচ্ছে না। মক পরীক্ষা ব্যবহার করা যাবে।";byId("btn-pyq-more").classList.add("hidden")}).finally(function(){pyqLoading=false;byId("btn-pyq-filter").disabled=false;byId("btn-pyq-more").disabled=false})}
  function pyqGroup(rows,key){var groups=new Map();rows.forEach(function(row){var value=String(row[key]===undefined||row[key]===null||row[key]===""?"অনির্দিষ্ট":row[key]);if(!groups.has(value))groups.set(value,[]);groups.get(value).push(row)});return groups}
  function renderPyq(){var container=byId("pyq-hierarchy");container.textContent="";if(!pyqRows.length){byId("pyq-status").textContent="এই ফিল্টারে কোনো মানব-যাচাইকৃত PYQ পাওয়া যায়নি।";byId("btn-pyq-more").classList.add("hidden");return}var levels=[{key:"examKey",prefix:"পরীক্ষা"},{key:"year",prefix:"বছর"},{key:"shift",prefix:"শিফট"},{key:"stageKey",prefix:"ধাপ"},{key:"paperKey",prefix:"পেপার"},{key:"sectionKey",prefix:"বিভাগ"}];appendPyqGroups(container,pyqRows,levels,0);byId("pyq-status").textContent=String(pyqRows.length)+" / "+String(pyqTotal)+"টি যাচাই করা প্রশ্ন দেখানো হচ্ছে।";byId("btn-pyq-more").classList.toggle("hidden",pyqRows.length>=pyqTotal)}
  function appendPyqGroups(container,rows,levels,depth){if(depth>=levels.length){rows.forEach(function(row){var article=document.createElement("article"),title=document.createElement("h3"),options=document.createElement("ol"),source=document.createElement("p");article.className="pyq-question";title.textContent="প্রশ্ন "+String(row.originalQuestionNumber||"—")+": "+String(row.question||"");(row.options||[]).forEach(function(option){var item=document.createElement("li");item.textContent=String(option);options.appendChild(item)});source.className="pyq-source";source.textContent=[row.language?"ভাষা: "+row.language:"",row.answerStatus?"অফিসিয়াল উত্তর: "+row.answerStatus:"",row.licenseCode?"লাইসেন্স: "+row.licenseCode:""].filter(Boolean).join(" · ");if(row.sourceUrl&&/^https:\/\//i.test(row.sourceUrl)){var link=document.createElement("a");link.href=row.sourceUrl;link.target="_blank";link.rel="noopener noreferrer";link.textContent=row.sourceTitle||"অফিসিয়াল উৎস";source.append(document.createTextNode(source.textContent?" · ":""),link)}article.append(title,options,source);container.appendChild(article)});return}var level=levels[depth];pyqGroup(rows,level.key).forEach(function(groupRows,value){var details=document.createElement("details"),summary=document.createElement("summary");details.className="pyq-group";details.open=depth<2;summary.textContent=level.prefix+": "+value+" ("+groupRows.length+")";details.appendChild(summary);appendPyqGroups(details,groupRows,levels,depth+1);container.appendChild(details)})}
  function renderIntro(){var draft=readDraft()||serverDraft();byId("intro-title").textContent=instance.title||"মক পরীক্ষা";byId("test-subtitle").textContent=(instance.testType||"mock").replace(/_/g," ")+" · "+sections.length+" বিভাগ";byId("intro-count").textContent=String(instance.questionCount||flat.length);byId("intro-marks").textContent=String(instance.totalMarks||0);byId("intro-time").textContent=instance.timeLimitSeconds?Math.ceil(instance.timeLimitSeconds/60)+" মিনিট":"বিভাগভিত্তিক";byId("intro-sections").textContent=String(sections.length);byId("resume-box").classList.toggle("hidden",!draft);byId("btn-resume").classList.toggle("hidden",!draft);byId("btn-discard").classList.toggle("hidden",!draft);show("intro")}
  function start(resume){if(!initData){showError("পরীক্ষা শুরু করতে Telegram-এর যাচাইকৃত Mini App বাটন ব্যবহার করুন।");return}var draft=resume?readDraft():null;if(!resume){discardDraft();answers={};marked={};responseTimes={}}if(draft)restoreDraft(draft);else attempt={clientAttemptId:uuid(),attemptId:null,deadlineAt:null};retryAction=function(){start(true)};show("loading");byId("loading-copy").textContent=resume?"সংরক্ষিত চেষ্টা ফেরত আনা হচ্ছে...":"নিরাপদ চেষ্টা শুরু হচ্ছে...";request("/api/tests/instances/"+encodeURIComponent(testId)+"/attempts/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:initData,clientAttemptId:attempt.clientAttemptId})}).then(function(progress){attempt=Object.assign(attempt,progress);mergeProgress(progress);currentSectionId=progress.currentSectionInstanceId||currentSectionId||sections[0].sectionInstanceId;saveDraft();openCurrentSection();renderQuestion();startTimer();show("test")}).catch(function(error){showError(["AUTH_REQUIRED","AUTH_EXPIRED"].indexOf(errorCategory(error))>=0?"Telegram যাচাই শেষ হয়েছে। Mini App আবার খুলুন।":"চেষ্টা শুরু করা যায়নি। একই attempt ID দিয়ে আবার চেষ্টা করুন।")})}
  function mergeProgress(progress){(progress.responses||[]).forEach(function(row){if(row.selectedIndex===null||[0,1,2,3].includes(row.selectedIndex))answers[row.questionId]=row.selectedIndex;marked[row.questionId]=!!row.markedForReview;responseTimes[row.questionId]=row.responseTimeSeconds||0})}
  function sectionIndex(){return Math.max(0,sections.findIndex(function(section){return section.sectionInstanceId===currentSectionId}))}
  function currentSection(){return sections[sectionIndex()]||sections[0]}
  function sectionQuestions(){return currentSection().questions||[]}
  function openCurrentSection(){var rows=sectionQuestions();if(!rows.length)return;currentIndex=Math.max(0,Math.min(currentIndex,rows.length-1));questionOpenedAt=Date.now()}
  function renderQuestion(){var section=currentSection(),rows=sectionQuestions(),question=rows[currentIndex];if(!question)return;byId("section-title").textContent=section.displayName||section.sectionKey||"বিভাগ";byId("question-position").textContent="প্রশ্ন "+(currentIndex+1)+" / "+rows.length;byId("question-text").textContent=question.question;var options=byId("options");options.textContent="";(question.options||[]).forEach(function(text,index){var button=document.createElement("button");button.type="button";button.className="option"+(answers[question.questionId]===index?" selected":"");button.setAttribute("role","radio");button.setAttribute("aria-checked",answers[question.questionId]===index?"true":"false");button.setAttribute("aria-label","বিকল্প "+(index+1)+": "+text);var key=document.createElement("span");key.textContent=String.fromCharCode(65+index);button.appendChild(key);button.appendChild(document.createTextNode(text));button.addEventListener("click",function(){selectAnswer(question.questionId,index)});options.appendChild(button)});byId("mark-review").checked=!!marked[question.questionId];byId("btn-bookmark").textContent=bookmarked[question.questionId]?"★ অনুশীলনে যোগ হয়েছে":"☆ অনুশীলনের জন্য বুকমার্ক";byId("btn-bookmark").disabled=false;byId("btn-previous").disabled=currentIndex===0;byId("btn-next").disabled=currentIndex===rows.length-1;var nextSection=sections[sectionIndex()+1];byId("btn-section").classList.toggle("hidden",!nextSection);renderSections();renderPalette();questionOpenedAt=Date.now();saveDraft()}
  function recordTime(questionId){var seconds=Math.max(0,(Date.now()-questionOpenedAt)/1000);responseTimes[questionId]=Math.round(((Number(responseTimes[questionId])||0)+seconds)*100)/100;questionOpenedAt=Date.now()}
  function selectAnswer(questionId,index){recordTime(questionId);answers[questionId]=index;marked[questionId]=!!byId("mark-review").checked;saveDraft();renderQuestion();queueSync()}
  function bookmarkCurrent(){var question=sectionQuestions()[currentIndex],button=byId("btn-bookmark");if(!question||!initData||bookmarked[question.questionId]||button.disabled)return;var questionId=question.questionId;button.disabled=true;button.textContent="বুকমার্ক হচ্ছে...";request("/api/me/bookmarks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:initData,itemType:"question",itemId:questionId,active:true})}).then(function(){bookmarked[questionId]=true;var currentQuestion=sectionQuestions()[currentIndex];if(currentQuestion&&currentQuestion.questionId===questionId){button.disabled=false;button.textContent="★ অনুশীলনে যোগ হয়েছে"}}).catch(function(){var currentQuestion=sectionQuestions()[currentIndex];if(currentQuestion&&currentQuestion.questionId===questionId){button.disabled=false;button.textContent="বুকমার্ক করা যায়নি—আবার চেষ্টা করুন"}})}
  function renderSections(){var strip=byId("section-strip"),idx=sectionIndex();strip.textContent="";sections.forEach(function(section,index){var item=document.createElement("span");item.className="section-pill"+(index===idx?" current":index<idx?" done":"");item.textContent=(index+1)+". "+(section.displayName||section.sectionKey);strip.appendChild(item)})}
  function renderPalette(){var palette=byId("palette");palette.textContent="";sectionQuestions().forEach(function(question,index){var button=document.createElement("button");button.type="button";button.textContent=String(index+1);button.className=(answers[question.questionId]!==undefined&&answers[question.questionId]!==null?"answered ":"")+(marked[question.questionId]?"marked ":"")+(index===currentIndex?"current":"");button.setAttribute("aria-label","প্রশ্ন "+(index+1)+(answers[question.questionId]!==undefined&&answers[question.questionId]!==null?", উত্তর দেওয়া":", উত্তর বাকি")+(marked[question.questionId]?", রিভিউ চিহ্ন":""));button.addEventListener("click",function(){recordTime(sectionQuestions()[currentIndex].questionId);currentIndex=index;renderQuestion()});palette.appendChild(button)})}
  function responsePayload(){return flat.filter(function(item){return Object.prototype.hasOwnProperty.call(answers,item.question.questionId)||marked[item.question.questionId]}).map(function(item){var id=item.question.questionId;return{questionId:id,selectedIndex:Object.prototype.hasOwnProperty.call(answers,id)?answers[id]:null,responseTimeSeconds:Number(responseTimes[id])||0,markedForReview:!!marked[id]}})}
  function setSync(message,state){var status=byId("sync-status");status.textContent=message;status.className="sync "+(state||"");byId("btn-sync-retry").classList.toggle("hidden",state!=="error")}
  function queueSync(){syncQueued=true;setSync("সিঙ্ক বাকি","pending");if(!syncing)saveProgress()}
  function saveProgress(){if(!attempt||!attempt.attemptId||!syncQueued)return Promise.resolve(true);if(syncing)return syncPromise;syncQueued=false;syncing=true;setSync("সিঙ্ক হচ্ছে...","pending");syncPromise=request("/api/tests/attempts/"+encodeURIComponent(attempt.attemptId)+"/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:initData,responses:responsePayload()})}).then(function(progress){mergeProgress(progress);setSync("সব উত্তর সিঙ্ক হয়েছে","ok");return true}).catch(function(){syncQueued=true;setSync("সিঙ্ক হয়নি—খসড়া নিরাপদ আছে","error");return false}).finally(function(){syncing=false;syncPromise=null;if(syncQueued&&navigator.onLine)window.setTimeout(saveProgress,500)});return syncPromise}
  function flushProgress(){if(syncing)return syncPromise.then(function(ok){return ok&&syncQueued?flushProgress():ok});if(syncQueued)return saveProgress().then(function(ok){return ok&&syncQueued?flushProgress():ok});return Promise.resolve(true)}
  function advanceSection(){recordTime(sectionQuestions()[currentIndex].questionId);queueSync();flushProgress().then(function(ok){if(!ok)return;var next=sections[sectionIndex()+1];if(!next)return;setSync("বিভাগ বদল হচ্ছে...","pending");request("/api/tests/attempts/"+encodeURIComponent(attempt.attemptId)+"/sections/advance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:initData,nextSectionInstanceId:next.sectionInstanceId})}).then(function(progress){attempt=Object.assign(attempt,progress);currentSectionId=progress.currentSectionInstanceId||next.sectionInstanceId;currentIndex=0;saveDraft();openCurrentSection();renderQuestion();startTimer();setSync("নতুন বিভাগ শুরু হয়েছে","ok")}).catch(function(){setSync("বিভাগ বদলানো যায়নি—আবার চেষ্টা করুন","error")})})}
  function showSubmit(){var answered=Object.keys(answers).filter(function(id){return answers[id]!==null}).length;byId("submit-copy").textContent=answered+"টি উত্তর দেওয়া, "+(flat.length-answered)+"টি স্কিপ। সাবমিটের পর উত্তর বদলানো যাবে না।";byId("submit-modal").classList.remove("hidden");byId("btn-submit-back").focus()}
  function hideSubmit(){byId("submit-modal").classList.add("hidden");byId("btn-submit").focus()}
  function submitAttempt(autoSubmit){if(!attempt||!attempt.attemptId)return;hideSubmit();autoSubmitPending=!!autoSubmit;recordTime(sectionQuestions()[currentIndex].questionId);queueSync();show("loading");byId("loading-copy").textContent=autoSubmit?"সময় শেষ—উত্তরপত্র জমা হচ্ছে...":"উত্তরপত্র জমা হচ্ছে...";flushProgress().then(function(ok){if(!ok){showError("উত্তর সিঙ্ক হয়নি। খসড়া নিরাপদ আছে; সংযোগ ফিরলে আবার সাবমিট করুন।");return}return request("/api/tests/attempts/"+encodeURIComponent(attempt.attemptId)+"/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:initData,autoSubmit:!!autoSubmit})}).then(function(result){autoSubmitPending=false;discardDraft();renderResult(result)}).catch(function(){showError("সাবমিট সম্পন্ন হয়েছে কি না নিশ্চিত নয়। একই attempt ID দিয়ে আবার চেষ্টা করুন।")})})}
  function startTimer(){clearInterval(timerHandle);updateTimer();timerHandle=setInterval(updateTimer,1000)}
  function deadline(){var state=(attempt.sections||[]).find(function(row){return row.sectionInstanceId===currentSectionId});var values=[attempt.deadlineAt,state&&state.deadlineAt].filter(Boolean).map(function(value){return new Date(value).getTime()}).filter(Number.isFinite);return values.length?Math.min.apply(Math,values):null}
  function updateTimer(){var end=deadline();if(!end){byId("timer").textContent="সময়সীমা নেই";return}var seconds=Math.max(0,Math.ceil((end-Date.now())/1000)),minutes=Math.floor(seconds/60),rest=seconds%60;byId("timer").textContent=String(minutes).padStart(2,"0")+":"+String(rest).padStart(2,"0");byId("timer").classList.toggle("low",seconds<=60);if(seconds<=0){clearInterval(timerHandle);submitAttempt(true)}}
  function renderResult(result){show("result");byId("result-status").textContent=result.status==="auto_submitted"?"সময় শেষে উত্তরপত্র স্বয়ংক্রিয়ভাবে জমা হয়েছে।":"আপনার উত্তরপত্র নিরাপদে জমা হয়েছে।";byId("result-net").textContent=String(result.netMarks||0);byId("result-negative").textContent=String(result.negativeMarks||0);byId("result-correct").textContent=String(result.correct||0);byId("result-wrong").textContent=String(result.wrong||0);byId("result-skipped").textContent=String(result.skipped||0);var cohort=result.rankCohort||{};byId("result-rank").textContent=cohort.rank?cohort.rank+" / "+cohort.size:"—";renderAnalysis(byId("section-analysis"),result.sections||[],function(row){return row.displayName||row.sectionKey},function(row){return "নেট "+(row.netMarks||0)+" · সঠিক "+(row.correct||0)+" · স্কিপ "+(row.skipped||0)});var topics=(result.topicAnalysis&&result.topicAnalysis.length?result.topicAnalysis:result.subjectAnalysis)||[];renderAnalysis(byId("topic-analysis"),topics,function(row){return row.topic||row.subjectKey||"বিষয়"},function(row){return "নেট "+(row.netMarks||0)+" · সঠিক "+(row.correct||0)+" · ভুল "+(row.wrong||0)})}
  function renderAnalysis(container,rows,label,value){container.textContent="";if(!rows.length){var empty=document.createElement("p");empty.textContent="এই বিশ্লেষণের তথ্য নেই।";container.appendChild(empty);return}rows.forEach(function(row){var item=document.createElement("div"),name=document.createElement("b"),score=document.createElement("span");item.className="analysis-row";name.textContent=label(row);score.textContent=value(row);item.appendChild(name);item.appendChild(score);container.appendChild(item)})}
  function showError(message){byId("error-copy").textContent=message;show("error")}
  function move(delta){var rows=sectionQuestions(),question=rows[currentIndex];if(question)recordTime(question.questionId);currentIndex=Math.max(0,Math.min(rows.length-1,currentIndex+delta));renderQuestion()}
  byId("catalog-search").addEventListener("input",renderCatalog);byId("catalog-type").addEventListener("change",renderCatalog);byId("btn-pyq-filter").addEventListener("click",function(){loadPyq(true)});byId("btn-pyq-more").addEventListener("click",function(){loadPyq(false)});byId("btn-start").addEventListener("click",function(){start(false)});byId("btn-resume").addEventListener("click",function(){start(true)});byId("btn-discard").addEventListener("click",function(){discardDraft();renderIntro()});byId("btn-retry").addEventListener("click",function(){retryAction()});byId("btn-sync-retry").addEventListener("click",saveProgress);byId("btn-bookmark").addEventListener("click",bookmarkCurrent);byId("btn-previous").addEventListener("click",function(){move(-1)});byId("btn-next").addEventListener("click",function(){move(1)});byId("btn-section").addEventListener("click",advanceSection);byId("btn-submit").addEventListener("click",showSubmit);byId("btn-submit-back").addEventListener("click",hideSubmit);byId("btn-submit-confirm").addEventListener("click",function(){submitAttempt(false)});byId("mark-review").addEventListener("change",function(){var question=sectionQuestions()[currentIndex];if(!question)return;marked[question.questionId]=byId("mark-review").checked;saveDraft();renderPalette();queueSync()});window.addEventListener("miniapp:network",function(event){if(event.detail.online&&(syncQueued||autoSubmitPending))saveProgress().then(function(ok){if(ok&&autoSubmitPending)submitAttempt(true)})});document.addEventListener("keydown",function(event){if(byId("screen-test").classList.contains("hidden"))return;if(["1","2","3","4"].includes(event.key)){var q=sectionQuestions()[currentIndex];if(q)selectAnswer(q.questionId,Number(event.key)-1)}else if(event.key==="ArrowLeft")move(-1);else if(event.key==="ArrowRight")move(1)});
  loadInstance();
})();
